server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZZZ
    default-property-inclusion: non_null
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://139.9.181.241:13307/cyber_auth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: STS2022mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 5
      max-active: 10
      max-wait: 10000
      time-between-eviction-runs-millis: 110000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1 from dual
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 80
      log-abandoned: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    host: 192.168.0.11
    port: 30772
    timeout: 10000
    lettuce:
      pool:
        max-idle: 20
        max-active: 100
        max-wait: 10000
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.cyber.authing.domain
